apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: anson1138/keystonejs
      docker:
        dockerfile: ./Dockerfile
      #context: keystonejs
    - image: anson1138/postgresql
      context: postgres-keystone
      #docker:
      #  dockerfile: ./Dockerfile
test:
  - image: anson1138/keystonejs
    custom:
      - command: npm test
      #- command: npm run test
        timeoutSeconds: 60
        #dependencies:
        #  paths:
        #  -  "*_test.go"
        #  -  "test.sh"
  
deploy:
  helm:
    releases:
      - name: config-common
        chartPath: ./deploy/config-common
        namespace: default
        valuesFiles:
        - ./deploy/config-common/values.yaml
      #- name: mongodb
      #  repo: https://charts.bitnami.com/bitnami
      #  remoteChart: mongodb
      #  namespace: default
      #  valuesFiles:
      #  - ./deploy/mongodb/values.yaml
      - name: postgresql
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        namespace: default
        valuesFiles:
        - ./deploy/postgresql/values.yaml
      #- name: kube-prometheus-stack
      #  repo: https://prometheus-community.github.io/helm-charts
      #  remoteChart: kube-prometheus-stack
      #  namespace: default
      #  version: 16.0.1
      #  #valuesFiles:
      #  #- ./deploy/postgresql/values.yaml
      - name: postgresql-createdb
        chartPath: ./deploy/postgresql-createdb
        namespace: default
        artifactOverrides:
          image: anson1138/postgresql
        imageStrategy:
          helm: {}
        valuesFiles:
        - ./deploy/postgresql-createdb/values.yaml
      - name: keystonejs
        chartPath: ./deploy/keystonejs
        namespace: default
        artifactOverrides:
          image: anson1138/keystonejs
        imageStrategy:
          helm: {}
        valuesFiles:
        - ./deploy/keystonejs/values.yaml
    #hooks:
    #  after:
    #    - container:
    #      command: npm test
    #      containerName: keystonejs*
    #      podName: keystonejs*
      


  